<Project>
    <PropertyGroup>
        <TargetFramework>net8.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>

        <AnalysisLevel>latest-all</AnalysisLevel>
        <AnalysisMode>All</AnalysisMode>

        <EnforceCodeStyleInBuild>true</EnforceCodeStyleInBuild>

        <TreatWarningsAsErrors>true</TreatWarningsAsErrors>

        <NoWarn>$(NoWarn);CA2007</NoWarn>
        <NoWarn>$(NoWarn);CA1812</NoWarn>
    </PropertyGroup>
</Project>